# GitHub Actions Workflow for Drink Crafter
#
# This workflow automates the build and release process.
# It triggers automatically whenever you push a new version tag
# (e.g., v1.0.0, v1.1.0) to your GitHub repository.
#
# The workflow will:
# 1. Build all firmware and filesystem components.
# 2. Automatically generate a manifest.json file for each board.
# 3. Commit the compiled binaries and manifests to the 'release_assets' directory.
# 4. Create a new GitHub Release and upload the same binaries as assets.

name: Create Release and Upload Binaries

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0, v1.1.0, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Download Bootstrap files
        run: |
          wget https://raw.githubusercontent.com/twbs/bootstrap/v5.3.2/dist/css/bootstrap.min.css -P data/
          wget https://raw.githubusercontent.com/twbs/bootstrap/v5.3.2/dist/js/bootstrap.bundle.min.js -P data/

      # --- Build All Components ---
      - name: Build firmware for esp32dev_8_channel
        run: pio run -e esp32dev_8_channel
      - name: Build firmware for xiao_c6_6channel
        run: pio run -e xiao_c6_6channel
      - name: Build Filesystem Image (shared)
        run: pio run --target buildfs -e esp32dev_8_channel

      - name: Prepare Release Assets and Manifests
        run: |
          mkdir -p release_assets
          
          # Prepare assets with unique names
          mv .pio/build/esp32dev_8_channel/firmware.bin release_assets/firmware-esp32dev_8_channel.bin
          mv .pio/build/esp32dev_8_channel/bootloader.bin release_assets/bootloader-esp32dev_8_channel.bin
          mv .pio/build/esp32dev_8_channel/partitions.bin release_assets/partitions-esp32dev_8_channel.bin
          mv .pio/build/xiao_c6_6channel/firmware.bin release_assets/firmware-xiao_c6_6channel.bin
          mv .pio/build/xiao_c6_6channel/bootloader.bin release_assets/bootloader-xiao_c6_6channel.bin
          mv .pio/build/xiao_c6_6channel/partitions.bin release_assets/partitions-xiao_c6_6channel.bin
          mv .pio/build/esp32dev_8_channel/littlefs.bin release_assets/littlefs.bin

          # Create manifest for esp32dev_8_channel with relative paths
          echo '{' > release_assets/manifest-esp32dev_8_channel.json
          echo '  "name": "Drink Crafter (ESP32 DevKit)",' >> release_assets/manifest-esp32dev_8_channel.json
          echo '  "builds": [' >> release_assets/manifest-esp32dev_8_channel.json
          echo '    {' >> release_assets/manifest-esp32dev_8_channel.json
          echo '      "chipFamily": "ESP32",' >> release_assets/manifest-esp32dev_8_channel.json
          echo '      "parts": [' >> release_assets/manifest-esp32dev_8_channel.json
          echo '        { "path": "bootloader-esp32dev_8_channel.bin", "offset": 32768 },' >> release_assets/manifest-esp32dev_8_channel.json
          echo '        { "path": "partitions-esp32dev_8_channel.bin", "offset": 57344 },' >> release_assets/manifest-esp32dev_8_channel.json
          echo '        { "path": "firmware-esp32dev_8_channel.bin", "offset": 65536 },' >> release_assets/manifest-esp32dev_8_channel.json
          echo '        { "path": "littlefs.bin", "offset": 2686976 }' >> release_assets/manifest-esp32dev_8_channel.json
          echo '      ]' >> release_assets/manifest-esp32dev_8_channel.json
          echo '    }' >> release_assets/manifest-esp32dev_8_channel.json
          echo '  ]' >> release_assets/manifest-esp32dev_8_channel.json
          echo '}' >> release_assets/manifest-esp32dev_8_channel.json

          # Create manifest for xiao_c6_6channel with relative paths
          echo '{' > release_assets/manifest-xiao_c6_6channel.json
          echo '  "name": "Drink Crafter (XIAO C6)",' >> release_assets/manifest-xiao_c6_6channel.json
          echo '  "builds": [' >> release_assets/manifest-xiao_c6_6channel.json
          echo '    {' >> release_assets/manifest-xiao_c6_6channel.json
          echo '      "chipFamily": "ESP32-C6",' >> release_assets/manifest-xiao_c6_6channel.json
          echo '      "parts": [' >> release_assets/manifest-xiao_c6_6channel.json
          echo '        { "path": "bootloader-xiao_c6_6channel.bin", "offset": 0 },' >> release_assets/manifest-xiao_c6_6channel.json
          echo '        { "path": "partitions-xiao_c6_6channel.bin", "offset": 32768 },' >> release_assets/manifest-xiao_c6_6channel.json
          echo '        { "path": "firmware-xiao_c6_6channel.bin", "offset": 65536 },' >> release_assets/manifest-xiao_c6_6channel.json
          echo '        { "path": "littlefs.bin", "offset": 2686976 }' >> release_assets/manifest-xiao_c6_6channel.json
          echo '      ]' >> release_assets/manifest-xiao_c6_6channel.json
          echo '    }' >> release_assets/manifest-xiao_c6_6channel.json
          echo '  ]' >> release_assets/manifest-xiao_c6_6channel.json
          echo '}' >> release_assets/manifest-xiao_c6_6channel.json

      - name: Commit Release Assets to Repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add release_assets/
          git commit -m "CI: Add/update release assets for ${{ github.ref }}" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Automated release for ${{ github.ref }}.
            
            Use the [Web Flasher](https://renebohne.github.io/drink_crafter/web_flasher.html) to install.
            
            The attached assets are the individual components for each board.
          files: release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
