# GitHub Actions Workflow for Drink Crafter
#
# This workflow automates the build and release process.
# It triggers automatically whenever you push a new version tag
# (e.g., v1.0.0, v1.1.0) to your GitHub repository.
#
# The workflow will:
# 1. Build the firmware and component binaries for both boards.
# 2. Build the single, shared LittleFS filesystem image.
# 3. Rename all binaries to have unique names.
# 4. Create a new GitHub Release and upload all the renamed binaries as assets.

name: Create Release and Upload Binaries

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0, v1.1.0, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Download Bootstrap files
        run: |
          wget https://raw.githubusercontent.com/twbs/bootstrap/v5.3.2/dist/css/bootstrap.min.css -P data/
          wget https://raw.githubusercontent.com/twbs/bootstrap/v5.3.2/dist/js/bootstrap.bundle.min.js -P data/

      # --- Build All Components ---
      - name: Build firmware for esp32dev_8_channel
        run: pio run -e esp32dev_8_channel
      - name: Build firmware for xiao_c6_6channel
        run: pio run -e xiao_c6_6channel
      - name: Build Filesystem Image (shared)
        run: pio run --target buildfs -e esp32dev_8_channel

      - name: Prepare Release Assets
        run: |
          mkdir release_assets
          mv .pio/build/esp32dev_8_channel/firmware.bin release_assets/firmware-esp32dev_8_channel.bin
          mv .pio/build/esp32dev_8_channel/bootloader.bin release_assets/bootloader-esp32dev_8_channel.bin
          mv .pio/build/esp32dev_8_channel/partitions.bin release_assets/partitions-esp32dev_8_channel.bin
          mv .pio/build/xiao_c6_6channel/firmware.bin release_assets/firmware-xiao_c6_6channel.bin
          mv .pio/build/xiao_c6_6channel/bootloader.bin release_assets/bootloader-xiao_c6_6channel.bin
          mv .pio/build/xiao_c6_6channel/partitions.bin release_assets/partitions-xiao_c6_6channel.bin
          mv .pio/build/esp32dev_8_channel/littlefs.bin release_assets/littlefs.bin

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Automated release for ${{ github.ref }}.
            
            Use the [Web Flasher](https://renebohne.github.io/drink_crafter/web_flasher.html) to install.
            
            The attached assets are the individual components for each board.
          files: release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
